---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
---

# Here are some plots

Making interactive plots in plotly. we'll make examples using the NYC airbnb dataset.

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

Do some initial data cleaning / subsetting.

```{r}
data(nyc_airbnb)

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(rating = review_scores_location / 2) |> #making it a 5 point scale, rather than out of 10
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) |>
  drop_na(rating) |>  
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500
  )
```


Use plotly to make some quick plots. 

First a scatter plot

```{r}
nyc_airbnb |> 
  mutate(text_label = str_c("Price ", price, "\nNeighbourhood: ", neighbourhood)) |> 
  plot_ly(
    x = ~lat, y = ~long, color = ~price, text = ~text_label,
    type = "scatter", mode = "markers", alpha = 0.5
  )
```

Next up - box plot.

```{r}
nyc_airbnb |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
  plot_ly(
    x = ~neighbourhood, y =~price, color = ~neighbourhood,
    type = "box", colors = "viridis")
```

Bar chart with number of rentals.

```{r}
nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |> 
  plot_ly(x = ~neighbourhood, y = ~n,
          type = "bar")
```

Heatmap

```{r}
plot_ly(
  z = volcano, type = "heatmap"
)
```

Choropleth

```{r}
plot_ly(
  type = "choropleth",
  locations = c( "AZ", "CA", "VT"), locationmode = "USA-states", colorscale = "Viridis",
  z = c(10, 20, 40)) |> 
  layout (geo = list (scope = "usa"))
```

Other examples of [plot.ly](https://images.plot.ly/plotly-documentation/images/r_cheat_sheet.pdf).